dist: xenial
language: python
python:
- '3.6'
cache: pip
install:
- pip install -r requirements.txt
jobs:
  include:
  - stage: test
    script: pylint crawler recipe_search
before_install:
- openssl aes-256-cbc -K $encrypted_92f26e22b8b0_key -iv $encrypted_92f26e22b8b0_iv
  -in configuration.py.enc -out configuration.py -d
