dist: xenial

language: python
  - "3.6"


install:
      - pip install --upgrade pip
      - pip install -r requirements.txt

jobs:
  include:
    - stage: test
      script: "pylint crawler recipe_search"